baseURL = 'https://neurobridge.cn/'
languageCode = 'zh-cn'
title = '脑脑客厅'

[module]
    # uncomment line below for temporary local development of module,
    # when using a 'theme' as a git submodule or git cloned files
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[params.footer]
  copyright = "[沪ICP备2025135615号-2](https://beian.miit.gov.cn/) 丨 © 2025 [XyZ](https://neuroxyz.cn)"

[markup.goldmark.renderer]
    unsafe = true

